name: Check if PR is intended for merging
on:
  pull_request:
    types:
      - opened
      - unlabeled
      - labeled

jobs:
  check:
    name: confirm-publish:required
    runs-on: ubuntu-latest
    steps:
      - if: ${{ !contains(github.event.pull_request.labels.*.name, 'merge-without-publishing') }}
        run: exit 1
