name: Check if PR is intended for merging
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - unlabeled
      - labeled

jobs:
  unlabel:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'publish-to-tap') && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      issues: read
      pull-requests: write
    outputs:
      label_removed: ${{ steps.remove_label.outputs.label_removed }}
    steps:
      - uses: actions/checkout@v6
      - name: Remove label
        id: remove_label
        run: |
          git fetch origin "refs/pull/${PULL_REQUEST}/head:local-pr"
          labels=$(gh pr view "$PULL_REQUEST" --repo "$GITHUB_REPOSITORY" --json labels --jq '.labels[].name')
          if [[ "$(git log local-pr -1 --format='%cn')" != "github-actions[bot]" ]] && grep -q '^publish-to-tap$' <<< "$labels"; then
            gh pr edit "$PULL_REQUEST" --repo "$GITHUB_REPOSITORY" --remove-label "publish-to-tap"
            echo 'label_removed=true' >> "$GITHUB_OUTPUT"
          fi
        env:
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check:
    name: confirm-publish:required
    runs-on: ubuntu-latest
    needs: unlabel
    if: ${{ always() }}
    steps:
      - if: ${{ (!contains(github.event.pull_request.labels.*.name, 'merge-without-publishing') && !contains(github.event.pull_request.labels.*.name, 'publish-to-tap')) || needs.unlabel.outputs.label_removed == 'true' }}
        run: |
          echo "Confirm merging without publish or run the publish workflow"
          exit 1
